### ISSUE TITLE
403 Missing Access (65001)

### ISSUE THREAD

**Issue by kms0219kms** [Garlic-Team/TicketBot#10]
Immediately after starting the bot, the error code 65001 comes out with 403 error. How do I solve this?

**Comment by kms0219kms** [comment]
Oh, it's good to erase Guild Only.

**Comment by xHyroM** [comment]
> Immediately after starting the bot, the error code 65001 comes out with 403 error. How do I solve this?

https://gcommands.js.org/guide/guide/faq/#q-i-keep-getting-the-error-403-missing-access

**Comment by kms0219kms** [comment]
Sorry, All of these intents are allowed, but this error occurs.

**Comment by xHyroM** [comment]
> 
> 
> Sorry, All of these intents are allowed, but this error occurs.

Just put your guildid in the command, and then invite the guild bot with scope application.commands. Discord Dev Panel -> Your Bot -> Oauth2 -> select bot & application.commands scope
