### ISSUE TITLE
Slash Command Error

### ISSUE THREAD

**Issue by kms0219kms** [Garlic-Team/TicketBot#11]
Deleted unused slash commands, which remain on the server, and the console indicates that they have been loaded into Cache.

**Comment by xHyroM** [comment]
Are you sure you cleared the commands both globally and from the guild? Maybe you created global maybe guild commands.

https://gcommands-slash-gui.netlify.app/

**Comment by kms0219kms** [comment]
![image](https://user-images.githubusercontent.com/67222970/131290280-62a48b8b-78dc-426c-8eaf-4d7c1feb0bc2.png)
but
![image](https://user-images.githubusercontent.com/67222970/131290318-8f4821d6-c578-4001-8432-da76cc7234ff.png)

**Comment by kms0219kms** [comment]
> Are you sure you cleared the commands both globally and from the guild? Maybe you created global maybe guild commands.
> 
> https://gcommands-slash-gui.netlify.app/

정확하게는 "/sendpanel"을 "/new"로 수정하기만 했습니다.
