### ISSUE TITLE
Missing Access

### ISSUE THREAD

**Issue by DsHas** [Garlic-Team/TicketBot#14]
Hello,
Please help, i don't know how fix this problem
![image](https://user-images.githubusercontent.com/86534688/139531432-4b343782-3730-4b8c-960a-0fd5538ef796.png)

**Comment by S222em** [comment]
https://gcommands.js.org/guide/guide/questions/missingacces/

**Comment by DsHas** [comment]
> https://gcommands.js.org/guide/guide/questions/missingacces/

i don't understand

**Comment by DsHas** [comment]
Thanks
