### ISSUE TITLE
Not adding confirm and cancel button

### ISSUE THREAD

**Issue by Bidetti** [Garlic-Team/TicketBot#5]
let yes = new MessageButton().setLabel("Confirmar").setEmoji("✅").setStyle("gray").setID(`ticket_close_yes_${buttonMember.user.id}`)
            let no = new MessageButton().setLabel("Cancelar").setEmoji("❌").setStyle("gray").setID(`ticket_close_no_${buttonMember.user.id}`)

            let msg = await ticketChannel.send(`${buttonMember.user} Você deseja fechar seu report?`, {components: new MessageActionRow().addComponent(yes).addComponent(no)})

**Comment by xHyroM** [comment]
Fixed. Thanks for report; https://github.com/Garlic-Team/GCommands/issues/39
